
# Add GPU Support
set(WITH_CYCLES_DEVICE_OPTIX    ON  CACHE BOOL "" FORCE)
set(WITH_CYCLES_CUDA_BINARIES   ON  CACHE BOOL "" FORCE)
set(WITH_CYCLES_CUBIN_COMPILER  OFF CACHE BOOL "" FORCE)
set(WITH_CYCLES_HIP_BINARIES    ON  CACHE BOOL "" FORCE)
